### ISSUE TITLE
Add CSP detection and do not replace placeholders in case CSP is active

### ISSUE THREAD

**Issue by cecob** [Daywalkerchen/awesome-extension#23]
![image](https://user-images.githubusercontent.com/71407229/208513749-d5a5dbd4-1ff2-4c15-be19-44b78dd6f659.png)
![image](https://user-images.githubusercontent.com/71407229/208514768-4deabee0-9740-4052-9d27-dfd1296d47ba.png)

**Comment by Absebo** [comment]
Will porobably be solved by #26
Locally hosted resources do not have a problem with CORS/CSP

> Web-accessible extension resources are not blocked by [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) or [CSP](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP).

See https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/web_accessible_resources

**Comment by cecob** [comment]
![image](https://user-images.githubusercontent.com/71407229/208674061-e7236ed1-8369-4ffa-8c2b-c5e51c7e8b05.png)
