### ISSUE TITLE
Add squirtle emote

### ISSUE THREAD

**Issue by Daywalkerchen** [Daywalkerchen/awesome-extension#9]
### Short Summary
- Choose emotes
- Add emotes to EMOTE list

### Examples
- https://betterttv.com/emotes/61cc587ec8cc7f36d52ae78a
- https://betterttv.com/emotes/607e0ac739b5010444d028c7

**Comment by Absebo** [comment]
+1 for the retro version

**Comment by cecob** [comment]
Good first issue, indeed.

To add more variety to the currently expressible emotions, I'd suggest: https://betterttv.com/emotes/62f166caecbd41815423a99c

**Comment by Daywalkerchen** [comment]
:squirtle:
